spring.datasource.url=jdbc:mariadb://192.168.56.182:3306/testdb
spring.datasource.username=tomcat
spring.datasource.password=tomcat123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.thymeleaf.cache=false
server.port=8080

